"""
Django settings for recipe_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from whitenoise.middleware import WhiteNoiseMiddleware
import boto3    #added for heroku
from django.conf import settings #added for heroku
from storages.backends.s3boto3 import S3Boto3Storage #added for heroku


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY','django-insecure-6@_7@6xrgu6%w0%q8@jd7*%cs^xv%apptftccfep(_&qk-plg@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['https://borecipesapp-d8aa2a381872.herokuapp.com','borecipesapp-d8aa2a381872.herokuapp.com', '127.0.0.1'] #added for heroku

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages', #added for heroku
    #recipe app-related apps
    'recipes',
    'users',
    'bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #added for heroku
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recipe_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'recipe_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#AUTH
LOGIN_URL = '/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    BASE_DIR / 'static'
]

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT= BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Heroku: Update database configuration from $DATABASE_URL.
import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Bucketeer settings for media files
BUCKETEER_AWS_ACCESS_KEY_ID = os.getenv('AKIAX7CRDYXP7CZDLEHM')
BUCKETEER_AWS_SECRET_ACCESS_KEY = os.getenv('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')
BUCKETEER_BUCKET_NAME_MEDIA = os.getenv('bucketeer-9240826f-2785-4ee7-8c30-d56e212ee58b')
BUCKETEER_BUCKET_REGION_MEDIA = os.getenv('us-east-1')
BUCKETEER_MEDIA_URL = os.getenv('BUCKETEER_MEDIA_URL')

# Bucketeer settings for static files
BUCKETEER_BUCKET_NAME_STATIC = os.getenv('BUCKETEER_BUCKET_NAME_STATIC')
BUCKETEER_BUCKET_REGION_STATIC = os.getenv('BUCKETEER_BUCKET_REGION_STATIC')
BUCKETEER_STATIC_URL = os.getenv('BUCKETEER_STATIC_URL')

# Storage classes for media and static files
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS S3 settings for Bucketeer media files
AWS_ACCESS_KEY_ID = BUCKETEER_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = BUCKETEER_AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = BUCKETEER_BUCKET_NAME_MEDIA
AWS_S3_REGION_NAME = BUCKETEER_BUCKET_REGION_MEDIA
AWS_S3_CUSTOM_DOMAIN = BUCKETEER_MEDIA_URL

# AWS S3 settings for Bucketeer static files
STATIC_URL = BUCKETEER_STATIC_URL
STATICFILES_DIRS = []
STATIC_ROOT = None
